Hw1 thread pool
Hotckiss/Java-2 pull request #3
Opened 2018-03-08 13:25 UTC by Hotckiss

2018-05-15 15:55 UTC, dzharkov requested changes

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
В чем смысл хранения .idea в репозитории для гредл проекта? Пока -2

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +                        tasks.notify();
Зачем этот вызов?

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +    public synchronized void shutdown() {
Мне кажется, метод shutdown должен завершаться только после завершения всех потоков. -1

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +    public synchronized void shutdown() {
Лишний synchronized, -0.5

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +            LightFutureAbstract<U> taskApply = new LightFutureThenApply<>(function, this);
" Метод thenApply не должен блокировать работу потока, если результат задачи X ещё не вычислен", -1

2018-05-15 15:55 UTC, dzharkov commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +            LightFutureAbstract<U> taskApply = new LightFutureThenApply<>(function, this);
Нужно добавить тест, который это проверяет

2018-05-19 21:05 UTC, Hotckiss commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +            LightFutureAbstract<U> taskApply = new LightFutureThenApply<>(function, this);
ok, sync по ифу

2018-05-19 21:05 UTC, Hotckiss commented on hw1ThreadPool/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
удалил

2018-05-19 21:06 UTC, Hotckiss commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +                        tasks.notify();
пожалуй что не нужен, раз тут только забираем

2018-05-19 21:06 UTC, Hotckiss commented on hw1ThreadPool/src/main/java/ru/spbau/kirilenko/hw1ThreadPool/ThreadPoolImpl.java
> +    public synchronized void shutdown() {
ok

2018-05-21 13:39 UTC, dzharkov approved these changes
Ок, 10/10

2018-08-17 20:14 UTC, merged