Tic tac
Hotckiss/Java-2 pull request #4
Opened 2018-03-22 21:47 UTC by Hotckiss

2018-04-30 09:40 UTC, dzharkov requested changes

2018-04-30 09:40 UTC, dzharkov commented on TicTac/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
В чем смысл хранения .idea в репозитории для гредл проекта? Пока -2

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/CurrentGameType.java
> +    private static int currentType = 0;
Почему game type -- это целое число, а не enum? -1

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/FieldPainter.java
> +    private static Canvas canvas;
Статичное состояние хуже синглтона, -1

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/controllers/GameController.java
> +        if (CurrentGameType.getCurrentType() == 0) {
Дублирование кода, -1

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/EasyGame.java
> +public class EasyGame extends AbstractGame {
Почитайте https://en.wikipedia.org/wiki/Composition_over_inheritance
Идея в том, что лучше сделать не абстрактный Game и абстрактный интерфейс для игрока
Пока -1

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/GameField.java
> +    private int[][] field = new int[3][3];
Опять же использование целых чисел вместо енума

2018-04-30 09:40 UTC, dzharkov commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/MyPair.java
> +public class MyPair<T, U> {
В большинстве случаев использование пар в публичных декларациях -- это так сказать, code smells

2018-05-05 18:49 UTC, Hotckiss commented on TicTac/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Просто нам говорили удалять только workspase, но раз не нужно то уберу

2018-05-05 18:51 UTC, Hotckiss commented on TicTac/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
"общекомандные настройки типа inspections в gradle.build не хранятся, так что и .idea тоже выкладывают, если такие настройки используются"

2018-05-05 18:51 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/CurrentGameType.java
> +    private static int currentType = 0;
Ну да, тут пожалуй поспешность в конце сделал

2018-05-05 18:52 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/FieldPainter.java
> +    private static Canvas canvas;
Как я понял, нужно стереть все статики, заприватить конструктор и сделать инстанс, сделал так

2018-05-05 18:53 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/controllers/GameController.java
> +        if (CurrentGameType.getCurrentType() == 0) {
На самом деле тут конструктор вообще не нужен(где дублируется), автоматически вызывается initialize()

2018-05-05 18:54 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/EasyGame.java
> +public class EasyGame extends AbstractGame {
Может сделал не так, но теперь есть один класс Game вообще без наследования, и в конструктор он принимает AIPlayer, а для него две реализации как раз, ни одна из них наследования не требует, они просто возвращают клетку по данному полю

2018-05-05 18:56 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/GameField.java
> +    private int[][] field = new int[3][3];
Нуу тут была зашита сложная логика, в стиле X==1, O==4, empty==0, тогда легко узнать победителю, произведение 64 или 1. А еще удобно узнавать, верно ли что игроку остался один ход для победы, то есть если сумма строки 8, то это только 4+4+0 и можно выиграть в 1 ход. Но в итоге переделал на енамы

2018-05-05 18:57 UTC, Hotckiss commented on TicTac/src/main/java/ru/spbau/kirilenko/hw3TicTac/logic/MyPair.java
> +public class MyPair<T, U> {
удалил совсем, сделал javafx.util.Pair

2018-05-05 19:02 UTC, Hotckiss commented
А вот к этому нет комментариев, но стоит 5.5 /10, так должно быть?
https://github.com/Hotckiss/Java-2/pull/3

2018-05-15 15:57 UTC, dzharkov approved these changes
Ок, 10/10

2018-05-15 15:58 UTC, dzharkov commented
Про #3: извиняюсь, не отправил ревью

2018-08-17 20:15 UTC, merged