Simple ftp console
Hotckiss/Java-2 pull request #6
Opened 2018-05-02 22:19 UTC by Hotckiss

2018-05-16 16:42 UTC, dzharkov requested changes
Текущая оценка: 6
Максимальная оценка: 9

2018-05-16 16:42 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +        public void run() {
Это можно было просто сделать функцией, и передать в `Thread` ссылку на метод

2018-05-16 16:42 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                    } catch (Exception e) {
Неаккуратная обработка ошибок.
Макс. Оценка -1

2018-05-16 16:42 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                        new Thread(new ListTask(queryResult, directoryName)).start();
Зачем отдельные таски-то параллельно выполнять?
Все равно же вывод смешается от каждой из них.
Пока -1

2018-05-16 16:42 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                new Thread(new ClientHandler(client)).start();
Вообще, ручное создание потоков инстансов `Thread` -- сомнительная практика. В частности это может привести к тому, что будет создано неконтролируемое число потоков, что приведет к деградации производительности JVM.
Проще всего воспользоваться тредпулом из `java.util.concurrent`.
Пока -1

2018-05-16 16:42 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                        while (written < total) {
Вместо этого лучше воспользоваться IOUtils из common-io.
Пока -1

2018-05-19 19:45 UTC, Hotckiss commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +        public void run() {
не особо понял как пропихнуть очень легко ссылку на метод -- там принимается сокет извне, и вроде как ссылка об этом не знает, или можно хитрее
А еще там теперь pool.submit который ссылку не хочет съедать

2018-05-19 19:47 UTC, Hotckiss commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                    } catch (Exception e) {
ну тут вроде и обрабатывать нечего на самом деле, тут EOF вылетает когда команд не остается, тогда просто нужно перестать общаться с этим пользователем, и кажется делать ничего не нужно, а так мусорный вывод получается если посмотреть по тестам

2018-05-19 19:47 UTC, Hotckiss commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                        new Thread(new ListTask(queryResult, directoryName)).start();
ok

2018-05-19 19:47 UTC, Hotckiss commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                new Thread(new ClientHandler(client)).start();
ok

2018-05-19 19:47 UTC, Hotckiss commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                        while (written < total) {
ok

2018-05-21 13:28 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +                    } catch (Exception e) {
Исключения делятся на два типа
1. Одни могут случаться на практике: NumberFormat/IO. Их нужно обрабатывать в зависимости от ситуации.
2. Вторые по идее происходить не должны, и по сути являются багой, и просто молча их проглатывать, мягко говоря, моветон

2018-05-21 13:28 UTC, dzharkov commented on SimpleFTP/src/main/java/ru/spbau/kirilenko/hw4SimpleFTP/Server.java
> +        public void run() {
Да, ссылку на метод похоже нельзя. Но можно лямбду, вызывающую метод. Это не критично, в принципе

2018-05-21 13:29 UTC, dzharkov approved these changes
Ок, 9/10

2018-08-17 20:16 UTC, merged