MyJUnit
Hotckiss/Java-2 pull request #9
Opened 2018-05-20 20:20 UTC by Hotckiss

2018-05-20 20:21 UTC, Hotckiss commented
lombok не собрался в travis

2018-05-26 09:15 UTC, dzharkov requested changes
Текущая оценка: 8.5

2018-05-26 09:15 UTC, dzharkov commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +    private static URLClassLoader classLoader;
Зачем это поле нужно? Пока -1

2018-05-26 09:15 UTC, dzharkov commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +    private static void showHelp() {
Показывать безусловый хелп -- странная затея. Пока -0.5

2018-05-26 09:15 UTC, dzharkov commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +        URL[] urls = new URL[paths.size()];
Здесь какой-то странно организованный код.
Почему не сделать просто функцию, которая вернет список загруженных классов (java.lang.Class), которые потом можно по очереди запускать?

2018-05-26 09:15 UTC, dzharkov commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Tester.java
> +    private static class InvocationError extends Error {
Вообще класс `Error` -- для каких-то совсем низкоуровневых ошибок JVM, когда программе очень плохо и она скорее всего не восстановится (OutOfMemoryError)

2018-05-26 18:02 UTC, Hotckiss commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +    private static void showHelp() {
показываю если было --help или -h

2018-05-26 18:03 UTC, Hotckiss commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +    private static URLClassLoader classLoader;
загружать классы? запихнул внутрь метода

2018-05-26 18:05 UTC, Hotckiss commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Tester.java
> +    private static class InvocationError extends Error {
просто из строчки .forEach(runner::run) исключения не особо полетели, поэтому так получилось, но они подменяются потом на исключения

2018-05-26 18:07 UTC, Hotckiss commented on MyJUnit/src/main/java/ru/spbau/kirilenko/Main.java
> +        URL[] urls = new URL[paths.size()];
просто на вход ему нужно передать массив cpasspathoв, и они складывались и передавались при создании, а потом классы и перебираются

2018-05-30 17:41 UTC, dzharkov approved these changes
Ок, 10/10

2018-08-17 20:18 UTC, merged